# Generated by Django 5.1.5 on 2025-01-31 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_was_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='was_read',
            new_name='is_read',
        ),
    ]
